### ISSUE TITLE
Fix YAML front matter for PA2

### ISSUE THREAD

**Issue by jvcasillas** [ds4ling/programming_assignments#81]
The instructions specify using the following front matter: 

```
title: "Programming assignment 2"  
author: "Your name"  
date: "Last update: `r Sys.Date()`"  
output:  
  github_document:  
    highlight: kate  
    keep_md: yes  
    theme: united
```

but the `github_document` output doesn't render with knitr options. 
Should change to this for future reference: 

```
title: "Programming assignment 2"  
author: "Your name"  
date: "Last update: 2023-02-05 21:50:47"  
output:  
  html_document:  
    highlight: kate  
    keep_md: yes  
    theme: united
```
